"use client"
import { AuthContextProvider } from '@/context/AuthContext'
import './globals.css'
import { Inter } from 'next/font/google'
import { useEffect } from 'react'



const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  useEffect(() => {
    //This code is executed in the browser
    console.log(window.innerWidth)
}, [])
  return (
    
    <html lang="en">
      <AuthContextProvider>
      <body className="body">{children}</body>
      </AuthContextProvider>
    </html>
  )
}
